### PR TITLE
Change required php version to >=7.2.5

### PR DESCRIPTION
**Pull request by hristokpopov**

### CODE REVIEW

**Comment by goetas** [comment]
can you please run the CI for 7.2.5 and 7.4 php versions?

**Comment by hristokpopov** [comment]
> can you please run the CI for 7.2.5 and 7.4 php versions?

I have added SF 5.4 run with PHP (7.2.5, 7.4)
SF 6 still runs with PHP (8.1, 8.2)

Is this acceptable?

https://github.com/hristokpopov/LocaleBundle/actions/runs/6361083915/job/17275271178?pr=2

**Comment by goetas** [comment]
thanks

**Comment by hristokpopov** [comment]
Thanks for the assistance and prompt responses

**Pull request merged**
