### PR TITLE
Add Symfony 2.7 to build matrix

### PR DESCRIPTION
**Pull request by xelaris**
symfony/phpunit-bridge is used to collect deprecation warnings

### CODE REVIEW

**Comment by lunetics** [comment]
I think some more work needs to be done to also get rid off the deprecation messages.

**Comment by xelaris** [comment]
@lunetics Sure. This PR should also serve as a first step to make the deprecations visible and to ensure the general compatibility with 2.7.

I made two more changes to make the tests green for now. Not sure if lunetics/LocaleBundle@2ed1a6d is the appropriate solution for the failing test. Could you have a look at it, please? I don't understand how it could work before, when sorting an array of `ChoiceView` objects by language name (the label?) by just using `sort()`.

**Comment by lunetics** [comment]
I think there was some changes in 2.7 for the form choicelist, gotta look that up later

**Comment by dbu** [comment]
the changes look sane to me.

**Comment by xelaris** [comment]
The tests should be green now, without just ignoring the deprecations. Most of them where caused by `MetaValidator`. It's the only place where I introduced changes yet, to avoid the deprecation in the working code. Everything else applies to the test code. For versions in which the old ExecutionContext is deprecated, the new one is used. In this case the deprecated one is used in a dedicated `LegacyLocaleInformationTest` test class, which is skipped otherwise. Maybe this should also be done for the other sub-classes of `BaseMetaValidator`.
The test class for `LocaleChoiceList` is renamed to `LegacyLocaleChoiceListTest` since the LocaleChoiceList inherits from the deprecated SimpleChoiceList. To get rid of these deprecations, I think a new from type should be created based on the new `ArrayChoiceList`.

There are more deprecations which seems to not be triggered by the unit tests (in `LocaleValidator`, `LocaleAllowedValidator` and `LocaleType`).

**Pull request merged**
