### PR TITLE
Update TargetInformationBuilder.php

### PR DESCRIPTION
**Pull request by Mondane**
The call to Intl::getLanguageBundle()->getLanguageName has 3 parameters, the second being the region (optional null). I've added this second parameter. Now, the locale is shown in the current laguage again.

### CODE REVIEW

**Comment by artursvonda** [comment]
@dbu, hi! When do you plan to release this?

**Comment by dbu** [comment]
@lunetics and @ikwattro are the maintainers of this bundle, they should decide on that.

**Comment by artursvonda** [comment]
@lunetics? @ikwattro? Any comment regarding this?

**Comment by ikwattro** [comment]
I'll check for making a new release today

**Comment by artursvonda** [comment]
Thanks, appreciate!

**Comment by ikwattro** [comment]
Tagged 2.4.4

**Comment by artursvonda** [comment]
Great! Thank you!

**Pull request merged**
