### PR TITLE
Dispatch an event when locale is guessed

### PR DESCRIPTION
**Pull request by eggyal**
Sites that prefer to determine locale from the requested URI (whether by domain, route or querystring) often wish to redirect requests that do not specify the locale in the URI to a version that does.

For example, perhaps requests for `http://www.example.com/p52/` should be redirected to `http://www.example.com/{_locale}/p52`; or requests for `http://www.example.org/p52` should be redirected to `http://www.{_locale}.example.org/p52`.

Currently I am handling this scenario in a catchall/default controller, within which I must detect whether the URI contains the locale before deciding on the appropriate response.  This is duplicating the work of the `RouterLocaleGuesser`.

I suppose one could invoke an instance of that guesser directly from the catchall/default controller to save on coding the tests oneself, but one would still be repeating work that has already been undertaken.

A better way would be for the `LocaleGuesserManager` to dispatch an event once it has determined the locale.  A custom listener could then handle the event and take appropriate action according to whichever guesser was successful.  For example, it could cause a redirection if the guesser was not of an acceptable type.

### CODE REVIEW

**Comment by eggyal** [comment]
I've just realised that dispatching this event doesn't solve my problem... since (obviously) the `RouterLocaleGuesser` can only obtain the locale from the requested path if the request was matched against a route containing `{_locale}`, I still need to create a default/catchall route and controller in order to learn anything useful from this event.

Perhaps the event may be useful in some other circumstances, so I'll leave the PR open for you to decide.

**Comment by dbu** [comment]
i am not sure if the event is that relevant. one can also just listen to
kernel request events with a priority after the router and the guesser
have kicked in and decide what to do.

for your scenario, i would look into a custom error handler that
investigates 404 errors and issues a redirect to the same path but with
locale, if it exists.

**Comment by eggyal** [comment]
@dbu [commented](https://github.com/lunetics/LocaleBundle/pull/164#issuecomment-106189731):

> one can also just listen to kernel request events with a priority after the router and the guesser
have kicked in and decide what to do.

But one wouldn't be able to determine from that which of the guessers succeeded in determining the locale, which is what I was trying to do here.

I agree that your 404 handler approach is the better solution for my particular scenario.  Thank you again for that suggestion—both here [and on StackOverflow](http://stackoverflow.com/a/30500003/623041).

**Comment by dbu** [comment]
ah ok, i see. but apart from debugging, i don't see why the particular guesser would be important. i don't want to be negative, but adding events (and code in general) without a clear use case increases the complexity of the bundle, so i am -1 on merging this.

**Comment by eggyal** [comment]
@dbu: Not taken to be negative at all.  I made the commits before I realised it was of no use to me; if nobody else can think of a use case, then I completely agree it shouldn't be merged.  Happy for the PR to be closed on that basis.

**Pull request closed without merging**
