### PR TITLE
[WIP] Symfony 3 support

### PR DESCRIPTION
**Pull request by Ma27**
this pull request supports everything from symfony 2.7 and 3.0

### CODE REVIEW

**Comment by Ma27** [comment]
ok except the form stuff everything should work now..

**Comment by Ma27** [comment]
don't know whether I manage to fix it today, the behavior of this ChoiceList is really odd now :/

**Comment by Ma27** [comment]
@dbu , @lunetics except the form issue everything seems ok now.
I digged a bit into that implementation and I guess that creating a new form type would be enough so we can remove the *LocaleChoiceList* class.
But I don't really understand this implementation: https://github.com/lunetics/LocaleBundle/blob/master/Form/Extension/ChoiceList/LocaleChoiceList.php#L60-L88

Could you please help me there?

**Comment by hacfi** [comment]
In the longrun we should replace the deprecated `symfony/locale` with the newer `symfony/intl`.

**Comment by hacfi** [comment]
@Ma27 I also doesn’t fully understand that implementation but I think it splits the list of locales into two sections: First the preferred locales from the `Accept-Language` header, then the rest. In 3.0 we just need to provide the `preferred_choices`: http://symfony.com/doc/current/reference/forms/types/choice.html#preferred-choices

**Comment by hacfi** [comment]
FYI: The related changes in the Form component were made in symfony/symfony#14050

**Comment by hacfi** [comment]
The issue with the Form ChoiceList is fixed in Sententiaregum/LocaleBundle#1

**Comment by lsmith77** [comment]
tests are all failing

@lunetics I guess we should put this into a new minor release or even major release.

**Comment by hacfi** [comment]
Will look into those failing tests and create another PR for Sententiaregum/LocaleBundle

**Comment by dbu** [comment]
i guess its time for a new major version of the local bundle that only supports symfony 2.7+ (or even 2.8+ if that is easier)...

**Comment by lunetics** [comment]
I'm in for 2.8+

Anyone wanna work on it tomorrow @dbu @hacfi ? I'm available on freenode / druid

cheers

**Comment by hacfi** [comment]
Will join you later @lunetics !

**Comment by hacfi** [comment]
WIP see https://github.com/Sententiaregum/LocaleBundle/pull/2

**Comment by AlexandreHagen** [comment]
Hi 
Do you know when that will merge ? 
Thanks !

**Comment by Ma27** [comment]
https://github.com/lunetics/LocaleBundle/tree/sf3-support

I think that it will go on here

**Comment by nurikabe** [comment]
What about `LocaleType`?

**Comment by server-may-cry** [comment]
Pls add support to download branch [sf3-support](https://github.com/lunetics/LocaleBundle/tree/sf3-support)  by composer.

**Comment by dbu** [comment]
@server-may-cry you can use `dev-sf3-support` in composer to use that branch.

**Comment by WouterJ** [comment]
Seems like all required PRs are merged, what is stopping this PR from merging? (and tagging a new release?) Anything I can help with?

**Comment by lsmith77** [comment]
looks good to me .. only question is if we discussed the bump to php 5.5

**Comment by lunetics** [comment]
Should 3.1 be included aswell now that it is out?

**Comment by WouterJ** [comment]
Yeah, but as 3.1 is backwards compatible with 3.0, tests on 3.1 will pass as well (and composer already allows 3.1).

**Comment by lunetics** [comment]
So i would say merge and release 2.5.0 ?

**Comment by lsmith77** [comment]
+1

**Comment by dbu** [comment]
+1

and maybe do a new PR to build with 3.1. it would not be the first time a regression comes up...

**Comment by dbu** [comment]
\o/

**Comment by AlexandreHagen** [comment]
Hi 
I am not sure that issue is on your side but when a tired to install Symfony 3.1 with LocaleBundle 2.5.1 I got this: 
```
Problem 1
    - Installation request for symfony/symfony 3.1.0 -> satisfiable by symfony/symfony[v3.1.0].
    - lunetics/locale-bundle 2.5.1 requires symfony/locale ^2.8|^3.0 -> satisfiable by symfony/locale[v2.8.6, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5].
    - symfony/locale v2.8.6 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.0 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.1 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.2 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.3 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.4 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.5 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.6 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/symfony[v3.0.6], symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - Can only install one of: symfony/symfony[v3.1.0, v3.0.6].
    - don't install symfony/intl v2.7.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.10|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.11|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.12|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.13|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.7|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.8|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.9|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.6|don't install symfony/symfony v3.1.0
    - Installation request for lunetics/locale-bundle 2.5.1 -> satisfiable by lunetics/locale-bundle[2.5.1].
```
I am confused. Release 2.5.1 do not support Symfony 3.1 ?

**Comment by server-may-cry** [comment]
@AlexandreHagen, provide your composer.json file and command you run

**Comment by AlexandreHagen** [comment]
My composer.json:
```JSON 
 "require": {
    "php": ">=5.5 <7.0.7",
    "ext-pdo": "*",
    "ext-pdo_pgsql": "*",
    "symfony/symfony": "3.1.0",
    "sensio/distribution-bundle": "5.0.6",
    "sensio/framework-extra-bundle": "3.0.16",
    "sensio/generator-bundle": "3.0.6",
    "doctrine/orm": "2.5.4",
    "doctrine/doctrine-bundle": "1.6.3",
    "twig/extensions": "1.3.0",
    "symfony/assetic-bundle": "2.8.0",
    "symfony/swiftmailer-bundle": "2.3.11",
    "symfony/monolog-bundle": "2.11.1",
    "incenteev/composer-parameter-handler": "2.1.2",
    "jms/security-extra-bundle": "1.6.0",
    "jms/di-extra-bundle": "1.7.1",
    "friendsofsymfony/user-bundle": "dev-master",
    "doctrine/doctrine-fixtures-bundle": "2.3.0",
    "oneup/flysystem-bundle": "1.4.1",
    "league/flysystem-cached-adapter": "1.0.3",
    "league/flysystem-rackspace": "1.0.5",
    "vich/uploader-bundle": "1.1.0",
    "friendsofsymfony/rest-bundle": "2.0.0-BETA2",
    "jms/serializer-bundle": "1.1.0",
    "lunetics/locale-bundle": "2.5.1",
    "nelmio/api-doc-bundle": " 2.12.0",
    "knplabs/knp-snappy-bundle": "1.4",
    "doctrine/doctrine-migrations-bundle": "1.1.1",
    "lexik/jwt-authentication-bundle": "1.5.1",
    "nelmio/cors-bundle": "1.4.1",
    "stripe/stripe-php": "3.14.1",
    "teknoo/sellsy-client": "1.0.4",
    "sllh/iso-codes-validator": "3.0",
    "guzzlehttp/guzzle": "6.2.0",
    "php-amqplib/rabbitmq-bundle": "1.10.0",
    "farmatholin/segment-io-bundle": "dev-master",
    "smart-core/accelerator-cache-bundle": "1.2.0",
    "julien-boudry/condorcet": "0.97.0",
    "hampe/zurb-ink-bundle": "2.1.0.0",
    "dunglas/api-bundle": "v2.0.0-alpha.1"

  },
  "require-dev": {
    "elao/web-profiler-extra-bundle": "~2.3@dev",
    "codeception/codeception": "2.1.*",
    "sensiolabs/security-checker": "@stable",
    "escapestudios/symfony2-coding-standard": "~2.0",
    "phpmd/phpmd" : "@stable",
    "sebastian/phpcpd": "~2.0",
    "flow/jsonpath": "~0.3"
  },
```
And I run ```composer update```

**Comment by WouterJ** [comment]
Fyi, in https://github.com/symfony-cmf/cmf-sandbox/pull/329 , I'm running this bundle 2.5.1 on Symfony 3.1, so it's definitely not a problem of this bundle.

**Comment by jonnnnyw** [comment]
I have the same issue as @AlexandreHagen. Symfony 3.1 will not install due to this package depending on 3.0.

**Comment by jonnnnyw** [comment]
Output from composer update

```
Problem 1
    - Installation request for symfony/symfony ~3.1 -> satisfiable by symfony/symfony[v3.1.0].
    - lunetics/locale-bundle 2.5.1 requires symfony/locale ^2.8|^3.0 -> satisfiable by symfony/locale[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6].
    - symfony/locale v2.8.0 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.1 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.2 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.3 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.4 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.5 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - symfony/locale v2.8.6 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - don't install symfony/intl v2.7.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.10|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.11|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.12|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.13|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.14|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.7|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.8|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.9|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.6|don't install symfony/symfony v3.1.0
    - Installation request for lunetics/locale-bundle ~2.5 -> satisfiable by lunetics/locale-bundle[2.5.1].
```

I have also tried a fresh composer install.

**Comment by AlexandreHagen** [comment]
The solution to me was to removed LocaleBundle in my project :(

**Comment by jonnnnyw** [comment]
As a temporary solution you can require symfony 3.1 aliased as 3.0 but I wouldn't want to rely on this long term as you will need to maintain your symfony version manually and could miss patch releases.

```
"require": {
        "symfony/symfony": "3.1.0 as 3.0.6",
        ...
```

Hopefully the `composer.json` for this package is updated to allow support for symfony 3.1 in the near future otherwise I too will have to remove it along with this workaround.

**Comment by jonnnnyw** [comment]
It turns out it's the `symfony/locale` bundle causing this. The [2.8.7 ](https://github.com/symfony/locale/blob/v2.8.7/composer.json) tag only supports Symfony 3.0.*.

The master branch however supports 3.* so you can alias the `symfony/locale` master branch as 2.8.7 to get around this. This isn't a huge deal as the `symfony/locale` package is deprecated anyway so I assume it is going to be removed from this bundle at some point.

```
"require": {
        "symfony/symfony": "~3.1",
        "symfony/locale": "dev-master as 2.8.7"
        ...
```

**Comment by dbu** [comment]
thanks for the workaround @jonnnnyw 

this PR is merged and closed. the issue was reported as #186, lets further discuss there

**Pull request merged**
