### PR TITLE
Added a DomainLocaleGuesser

### PR DESCRIPTION
**Pull request by coudenysj**
As discussed in #141, here is the PR to include a `DomainLocaleGuesser`.

### CODE REVIEW

**Comment by lunetics** [comment]
Released 2.4.1

Maybe backporting to 2.3 also

**Comment by coudenysj** [comment]
Thanks for the merge.

**Comment by dbu** [comment]
very cool @coudenysj !

@lunetics i would not backport new features to 2.3, once there is a 2.4 the 2.3 should only see bugfixes to minimize the risk of breaking things (and to reduce workload)

**Comment by lunetics** [comment]
yep, you are right :) we should rather encourage updating to 2.4 :)

**Pull request merged**
